version: '3.3'

services:
  hub:
    image: selenium/hub:3.7.1
    ports:
      - "4449:4444"
    deploy:
      placement:
        constraints:
          - engine.labels.stage == qa
    environment:
      - GRID_BROWSER_TIMEOUT=60000
      - GRID_TIMEOUT=90000
      - GRID_MAX_SESSION=50
      - GRID_CLEAN_UP_CYCLE=60000
      - GRID_UNREGISTER_IF_STILL_DOWN_AFTER=180000
      - GRID_NEW_SESSION_WAIT_TIMEOUT=120000
    labels:
      com.docker.ucp.access.label: "qa-automation"

  firefox:
    image: selenium/node-firefox:3.7.1
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    ports:
      - "5555:5555"
    deploy:
      replicas: 1
      placement:
        constraints:
          - engine.labels.stage == qa
    labels:
      com.docker.ucp.access.label: "qa-automation"

  chrome:
    image: selenium/node-chrome:3.7.1
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    ports:
      - "5556:5556"
    deploy:
      replicas: 1
      placement:
        constraints:
          - engine.labels.stage == qa
    labels:
      com.docker.ucp.access.label: "qa-automation"

  414px:
    image: selenium/node-chrome:3.7.1
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    ports:
      - "5557:5557"
    deploy:
      replicas: 1
      placement:
        constraints:
          - engine.labels.stage == qa
    labels:
      com.docker.ucp.access.label: "qa-automation"

  736px:
    image: selenium/node-chrome:3.7.1
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    ports:
      - "5558:5558"
    deploy:
      replicas: 1
      placement:
        constraints:
          - engine.labels.stage == qa
    labels:
      com.docker.ucp.access.label: "qa-automation"

  768px:
    image: selenium/node-chrome:3.7.1
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    ports:
      - "5559:5559"
    deploy:
      replicas: 1
      placement:
        constraints:
          - engine.labels.stage == qa
    labels:
      com.docker.ucp.access.label: "qa-automation"

  1024px:
    image: selenium/node-chrome:3.7.1
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    ports:
      - "5560:5560"
    deploy:
      replicas: 1
      placement:
        constraints:
          - engine.labels.stage == qa
    labels:
      com.docker.ucp.access.label: "qa-automation"
